import React, { FunctionComponent, ReactElement } from 'react';
import styles from '@styles/components/AppLayout.module.scss';
import WorkspaceNavbar from './WorkspaceNavbar';
import Head from 'next/head';

type WorkspaceLayoutProps = {
  children: ReactElement;
};

const WorkspaceLayout: FunctionComponent<WorkspaceLayoutProps> = ({
  children
}: WorkspaceLayoutProps) => {
  return (
    <>
      <div className={`${styles.topNavigationLayout} ${styles.workspaceLayout}`}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <WorkspaceNavbar projectName='The Consumer Trap' />
        <div className={`${styles.leftNavigationLayout}`}>{children}</div>
      </div>
    </>
  );
};
export default WorkspaceLayout;
